# Version 1.0.0
version: 2.1

##########################
# Common Definitions
##########################
aliases:
  - &project_dir "~/circleci-trigger-bot"

executors:
  node-exec:
    docker:
      - image: circleci/node:12.13.0
    working_directory: *project_dir
    resource_class: medium

##########################
# Workflow Definitions 
##########################
workflows:
  version: 2
  build-test:
    jobs:
      - test

##########################
# Job Definitions 
##########################
jobs:
  test:
    executor: node-exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: mkdir -p test-results/jest && yarn test
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-results/jest"
      - store_test_results:
          path: ./test-results
